"""
Generated by Cursor Agent from: requirements/add_to_cart.md
Prompt used:
    Generate a new Playwright+pytest UI test that satisfies requirements/add_to_cart.md.
    Follow our rules in prompts/authoring.md and match the style of test_homepage_cart.py.
    Save the result as tests/ui/test_add_to_cart_req.py.

Date: 2025-10-01
"""

"""Requirement: As a shopper, when I add one item to the cart, the cart count
should display 1."""

from playwright.sync_api import Page
from utils.api_helpers import reset_cart
from utils.ui_helpers import (
    go_home,
    get_cart_count,
    expect_cart_count,
)

def test_add_single_item_sets_cart_count_to_one(page: Page, base_url: str) -> None:
    """After adding a single item from a clean state, cart count shows 1."""
    # Arrange: reset cart and open homepage
    reset_cart(page.request)
    go_home(page, base_url)

    # Sanity: cart starts at 0
    assert get_cart_count(page) == 0

    # Act: add the first item via its form button
    item_form = page.locator('form:has(input[name="itemId"][value="1"])')
    item_form.get_by_role("button").click()

    # Assert: cart badge shows 1
    expect_cart_count(page, 1)


